question_data = [{"category": "Science: Mathematics", "type": "multiple", "difficulty": "hard",
                  "question": "How many zeptometres are inside one femtometre?",
                  "correct_answer": "1,000,000", "incorrect_answers": ["10", "1,000,000,000", "1000"]},
                 {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                  "question": "The difference between the lengths of a Boeing 777-300ER and an "
                              "Airbus A350-1000 is closest to:",
                  "correct_answer": "0.1m", "incorrect_answers": ["1m", "10m ", "100m"]},
                 {"category": "Geography", "type": "multiple", "difficulty": "hard",
                  "question": "The Hunua Ranges is located in...", "correct_answer": "New Zealand",
                  "incorrect_answers": ["Nepal", "China", "Mexico"]},
                 {"category": "Animals", "type": "multiple", "difficulty": "hard",
                  "question": "Which of these animals is NOT a lizard?", "correct_answer": "Tuatara",
                  "incorrect_answers": ["Komodo Dragon", "Gila Monster", "Green Iguana"]},
                 {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "hard",
                  "question": "Which board game was first released on February 6th, 1935?",
                  "correct_answer": "Monopoly", "incorrect_answers": ["Risk", "Clue", "Candy Land"]},
                 {"category": "Entertainment: Music", "type": "multiple", "difficulty": "hard",
                  "question": "Who designed the album cover for True Romance, an album by Estelle?",
                  "correct_answer": "Rebecca Sugar",
                  "incorrect_answers": ["Matt Burnett", "Ian Jones Quartey", "Ben Leven"]},
                 {"category": "Entertainment: Comics", "type": "multiple", "difficulty": "hard",
                  "question": "What is the real hair colour of the mainstream comic book "
                              "version (Earth-616) of Daredevil?",
                  "correct_answer": "Blonde", "incorrect_answers": ["Auburn", "Brown", "Black"]},
                 {"category": "Entertainment: Musicals & Theatres", "type": "multiple",
                  "difficulty": "hard",
                  "question": "Who serves as the speaker of the prologue in "
                              "Shakespeare&#039;s Romeo and Juliet?",
                  "correct_answer": "Chorus", "incorrect_answers": ["Montague", "Refrain", "Capulet"]},
                 {"category": "Entertainment: Comics", "type": "multiple", "difficulty": "hard",
                  "question": "In the &quot;Archie&quot; comics, who was Jughead&#039;s "
                              "first girlfriend?",
                  "correct_answer": "Joani", "incorrect_answers": ["Ethel", "Debbi", "Margret"]},
                 {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
                  "question": "In &quot;Star Trek Nemesis&quot;, why was Praetor Shinzon created?",
                  "correct_answer": "To replace Picard as a Romulan Agent",
                  "incorrect_answers": ["To destroy the Enterprise", "To become Picard&#039;s friend ",
                                        "To steal the Enterprise"]},
                 {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
                  "question": "What is the unit of electrical inductance?", "correct_answer": "Henry",
                  "incorrect_answers": ["Weber", "Coulomb", "Mho"]},
                 {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
                  "question": "In &quot;Team Fortress 2&quot;, what is the fastest taunt kill "
                              "that can be pulled off?",
                  "correct_answer": "Showdown",
                  "incorrect_answers": ["Hadouken", "Organ Grinder", "Skewer"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "multiple",
                  "difficulty": "hard",
                  "question": "In the &quot;Star Wars&quot; universe, what species is Grand "
                              "Admiral Thrawn?",
                  "correct_answer": "Chiss",
                  "incorrect_answers": ["Gungans", "Pantorans", "Twi&#039;lek"]},
                 {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
                  "question": "How long is a light-year?",
                  "correct_answer": "9.461 Trillion Kilometres",
                  "incorrect_answers": ["1 AU", "105.40 Earth-years", "501.2 Million Miles"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                  "difficulty": "hard",
                  "question": "Which animation studio produced &quot;Sword Art Online&quot;?",
                  "correct_answer": "A-1 Pictures",
                  "incorrect_answers": ["Production I.G", "Silver Link", "Kyoto Animation"]},
                 {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
                  "question": "The Quadrangularis Reversum is best described as which of the "
                              "following?",
                  "correct_answer": "A percussion instrument",
                  "incorrect_answers": ["A building in Oxford University", "A chess move",
                                        "A geometric theorem"]},
                 {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
                  "question": "What Pok&eacute;mon&#039;s Base Stat Total does not change "
                              "when it evolves?",
                  "correct_answer": "Scyther", "incorrect_answers": ["Pikachu", "Sneasel", "Larvesta"]},
                 {"category": "Sports", "type": "multiple", "difficulty": "hard",
                  "question": "Which city features all of their professional sports "
                              "teams&#039; jersey&#039;s with the same color scheme?",
                  "correct_answer": "Pittsburgh",
                  "incorrect_answers": ["New York", "Seattle", "Tampa Bay"]},
                 {"category": "Sports", "type": "multiple", "difficulty": "hard",
                  "question": "Which player &quot;kung-fu kicked&quot; a Crystal "
                              "Palace fan in January 1995?",
                  "correct_answer": "Eric Cantona",
                  "incorrect_answers": ["David Seamen", "Ashley Cole", "Mark Hughes"]},
                 {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
                  "question": "In Left 4 Dead, what is the character Bill&#039;s last name?",
                  "correct_answer": "Overbeck", "incorrect_answers": ["Fish", "Roberts", "Stevenson"]}]
